don't automatically push changes out

diff --git a/buildshim b/buildshim
--- a/buildshim
+++ b/buildshim
@@ -8,13 +8,13 @@ install_deps)
     git submodule update
     ;;
 configure)
-    echo $HOME
-    if [[ -s "$HOME/hosts.buildbot" ]] ; then
-      cp $HOME/hosts.buildbot hosts.buildbot
-    else
-      printf "Can't upload and deploy, can't find hosts.buildbot file"
-      exit 1
-    fi
+    #echo $HOME
+    #if [[ -s "$HOME/hosts.buildbot" ]] ; then
+    #  cp $HOME/hosts.buildbot hosts.buildbot
+    #else
+    #  printf "Can't upload and deploy, can't find hosts.buildbot file"
+    #  exit 1
+    #fi
     ;;
 compile)
     ;;
@@ -24,7 +24,7 @@ check)
 package)
     ;;
 upload)
-    ansible-playbook -i hosts.buildbot site.yml
+    #ansible-playbook -i hosts.buildbot site.yml
     ;;
 compile_extra)
     ;;
